export const SELECT_BREAKFAST = "SELECT_BREAKFAST";
export const SELECT_MEAL = "SELECT_MEAL";
export const ADD_CLIENT_NAME = "ADD_CLIENT_NAME";
export const ADD_TICKET_ITEM = "ADD_TICKET_ITEM";
export const EDIT_TICKET_ITEM = "EDIT_TICKET_ITEM";
export const DELETE_TICKET_ITEM = "DELETE_TICKET_ITEM";
export const SEND_ORDER = "SEND_ORDER";
export const CLEAN_FOR_NEW_ORDER = "CLEAN_FOR_NEW_ORDER";
